name: Scala CI

on:
  push:
    branches: [ master, main, development ]
  pull_request:
    branches: [ master, main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: compile
      run: sbt compile
